### ISSUE TITLE
Animate the doors

### ISSUE THREAD

**Issue by shiffman** [Lumon-Industries/Macrodata-Refinement#3]
The doors of the bins animate open and the bin slides out and back in then the doors close.

**Comment by ArztKlein** [comment]
Hello, I'll add this feature. Just want to let you all know to prevent anyone's time from being wasted

**Comment by ArztKlein** [comment]
Does anyone have a video where we can see the doors opening/closing? Just want to make the animation as accurate as possible

**Comment by shiffman** [comment]
Here is a clip I found that shows the doors opening https://youtu.be/Gnffe374Upw

**Comment by shiffman** [comment]
I've seen other clips where the rectangle with the 4 bars then slides out, if I can find one I'll post here

**Comment by shiffman** [comment]
Re-opening to address one tiny issue related to how the "tray" slides out—you can see it peeking out behind the other rectangles below! I think maybe I'll just draw an extra solid rectangle underneath in between?

![up_and_down](https://user-images.githubusercontent.com/191758/162662055-0fb2f69d-bce7-4077-a4f3-8b1afd377c97.gif)

**Comment by shiffman** [comment]
@ArztKlein let me now if #24 looks ok to you!

**Comment by ArztKlein** [comment]
@shiffman Looks great. Apologies for that, it went completely over my head!
