### ISSUE TITLE
Local Storage?

### ISSUE THREAD

**Issue by shiffman** [Lumon-Industries/Macrodata-Refinement#7]
Welcomes you back and tells you about your data refining progress

**Comment by shiffman** [comment]
How many coordinates did you refine? Are you Refiner of the Quarter? What else can we track?

**Comment by jhrtn** [comment]
Working on this now in conjunction with #26

Currently I'm saving a **macrodata file** object in local storage which contains the filename (per #26) along with the bin values, so when we refresh the page the bin values are populated from local storage the percentage is correct

https://user-images.githubusercontent.com/17256474/164775534-78f4b2e5-bbd5-45da-b98f-4911a706c1a2.mp4

**Comment by shiffman** [comment]
Local storage is working! Let's open new issues for additional things we want to track.
